-- MySQL Script generated by MySQL Workbench
-- Sun Mar  1 14:57:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titolo` VARCHAR(45) NOT NULL,
  `autore` VARCHAR(45) NOT NULL,
  `editore` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `quantita` VARCHAR(45) NOT NULL,
  `corsia` VARCHAR(45) NULL DEFAULT NULL,
  `libreria` VARCHAR(45) NULL DEFAULT NULL,
  `scaffale` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`utente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cognome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `via` VARCHAR(45) NULL DEFAULT NULL,
  `civico` VARCHAR(45) NULL DEFAULT NULL,
  `citta` VARCHAR(45) NULL DEFAULT NULL,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  `cap` VARCHAR(45) NULL DEFAULT NULL,
  `ruolo` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `biblioteca`.`prestito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`prestito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fkIdUtente` INT(11) NULL DEFAULT NULL,
  `fkIdLibro` INT(11) NULL DEFAULT NULL,
  `dataInizio` VARCHAR(45) NOT NULL,
  `dataConsegna` VARCHAR(45) NULL DEFAULT NULL,
  `dataUltimoSollecito` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fkIdUtente_idx` (`fkIdUtente` ASC) VISIBLE,
  INDEX `fkIdLibro_idx` (`fkIdLibro` ASC) VISIBLE,
  CONSTRAINT `fkIdLibro`
    FOREIGN KEY (`fkIdLibro`)
    REFERENCES `biblioteca`.`libro` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdUtente`
    FOREIGN KEY (`fkIdUtente`)
    REFERENCES `biblioteca`.`utente` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
